server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: event
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    web:
      page-serialization-mode: via-dto